### ISSUE TITLE
erro

### ISSUE THREAD

**Issue by tqangxl** [weihomechen/angular4-admin#2]
|   +-- semver-diff@2.1.0
|   `-- xdg-basedir@3.0.0
+-- typescript@2.2.2
+-- zone.js@0.8.11
`-- ztree@3.5.24

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN ng2-translate@5.0.0 requires a peer of @angular/core@^2.0.0 but none was installed.
npm WARN ng2-translate@5.0.0 requires a peer of @angular/http@^2.0.0 but none was installed.

D:\Dev\GitHub\angular4-admin>
D:\Dev\GitHub\angular4-admin>
D:\Dev\GitHub\angular4-admin>
D:\Dev\GitHub\angular4-admin>ng serve
Your global Angular CLI version (1.1.0) is greater than your local
version (1.0.3). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200 **
Hash: a5ee4331dccdcac523b6
Time: 61409ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 158 kB {5} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 196 kB {4} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 489 kB {5} [initial] [rendered]
chunk    {3} scripts.bundle.js, scripts.bundle.js.map (scripts) 1.24 MB {5} [initial] [rendered]
chunk    {4} vendor.bundle.js, vendor.bundle.js.map (vendor) 5.78 MB [initial] [rendered]
chunk    {5} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in D:/Dev/GitHub/angular4-admin/node_modules/@angular/platform-browser/animations/src/animation_renderer.d.ts (1,53): Cannot find module '@angular/animations/browser'.

ERROR in D:/Dev/GitHub/angular4-admin/node_modules/@angular/platform-browser/animations/src/providers.d.ts (8,276): Cannot find module '@angular/animations/browser'.

ERROR in D:/Dev/GitHub/angular4-admin/src/app/animations/fade-in.ts (1,53): Cannot find module '@angular/animations'.

ERROR in D:/Dev/GitHub/angular4-admin/src/app/animations/fly-in.ts (1,71): Cannot find module '@angular/animations'.

ERROR in D:/Dev/GitHub/angular4-admin/node_modules/@angular/material/typings/dialog/dialog-container.d.ts (2,32): Cannot find module '@angular/animations'.

ERROR in D:/Dev/GitHub/angular4-admin/node_modules/@angular/material/typings/menu/menu-animations.d.ts (1,42): Cannot find module '@angular/animations'.

ERROR in D:/Dev/GitHub/angular4-admin/node_modules/@angular/material/typings/select/select-animations.d.ts (1,42): Cannot find module '@angular/animations'.

ERROR in D:/Dev/GitHub/angular4-admin/node_modules/@angular/material/typings/snack-bar/snack-bar-container.d.ts (2,32): Cannot find module '@angular/animations'.

ERROR in D:/Dev/GitHub/angular4-admin/node_modules/@angular/material/typings/tabs/tab-body.d.ts (2,32): Cannot find module '@angular/animations'.

ERROR in D:/Dev/GitHub/angular4-admin/node_modules/@angular/material/typings/tooltip/tooltip.d.ts (2,32): Cannot find module '@angular/animations'.

ERROR in Error encountered resolving symbol values statically. Could not resolve @angular/animations/browser relative to D:/Dev/GitHub/angular4-admin/node_modules/@angular/platform-browser/animations/index.d.ts., resolving symbol ɵe in D:/Dev/GitHub/angular4-admin/node_modules/@angular/platform-browser/animations/index.d.ts, resolving symbol BrowserAnimationsModule in D:/Dev/GitHub/angular4-admin/node_modules/@angular/platform-browser/animations/index.d.ts, resolving symbol BrowserAnimationsModule in D:/Dev/GitHub/angular4-admin/node_modules/@angular/platform-browser/animations/index.d.ts

ERROR in D:/Dev/GitHub/angular4-admin/src/app/animations/fade-in.ts (1,53): Cannot find module '@angular/animations'.

ERROR in D:/Dev/GitHub/angular4-admin/src/app/animations/fly-in.ts (1,71): Cannot find module '@angular/animations'.

ERROR in ./src/app/animations/fade-in.ts
Module not found: Error: Can't resolve '@angular/animations' in 'D:\Dev\GitHub\angular4-admin\src\app\animations'
 @ ./src/app/animations/fade-in.ts 1:0-74
 @ ./src/app/base-data/person-list/person-list.component.ts
 @ ./src/app/app.routing.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./src/app/animations/fly-in.ts
Module not found: Error: Can't resolve '@angular/animations' in 'D:\Dev\GitHub\angular4-admin\src\app\animations'
 @ ./src/app/animations/fly-in.ts 1:0-92
 @ ./src/app/share/app-ckeditor/app-ckeditor.component.ts
 @ ./src/app/app.routing.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/@angular/material/@angular/material.es5.js
Module not found: Error: Can't resolve '@angular/animations' in 'D:\Dev\GitHub\angular4-admin\node_modules\@angular\material\@angular'
 @ ./~/@angular/material/@angular/material.es5.js 20:0-81
 @ ./src/app/base-data/base-data.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/@angular/platform-browser/@angular/platform-browser/animations.es5.js
Module not found: Error: Can't resolve '@angular/animations/browser' in 'D:\Dev\GitHub\angular4-admin\node_modules\@angular\platform-browser\@angular\platform-browser'
 @ ./~/@angular/platform-browser/@angular/platform-browser/animations.es5.js 13:0-249
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/ng2-toastr/src/toast-container.component.js
Module not found: Error: Can't resolve '@angular/animations' in 'D:\Dev\GitHub\angular4-admin\node_modules\ng2-toastr\src'
 @ ./~/ng2-toastr/src/toast-container.component.js 4:19-49
 @ ./~/ng2-toastr/ng2-toastr.js
 @ ./src/app/share/share.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
webpack: Failed to compile.
^C终止批处理操作吗(Y/N)?

**Comment by tqangxl** [comment]
"@angular/platform-browser": "4.1.3",
	"@angular/core": "2.0.0",
	"@angular/http": "2.0.0",

**Comment by tqangxl** [comment]
"@angular/platform-browser": "4.1.3",
	"@angular/core": "2.0.0",
	"@angular/http": "2.0.0",
  	"@angular/animations": "^4.0.0",

**Comment by weihomechen** [comment]
Hi,it seems that I forget add animations module to dependencies. A stupid mistakess... try update the project.By the way, you should be a chinese, right? 你会讲中文吧？

**Comment by weihomechen** [comment]
Hi,it seems that I forget add animations module to dependencies. A stupid mistakess... try update the project.By the way, you should be a chinese, right? 你会讲中文吧？
